version: '3'

services:
  symfony:
    container_name: symfony
    build: .
    ports:
      - "9091:8000"
    command: "symfony server:start"
    volumes:
      - ./hello-world:/var/www/html
  #   depends_on:
  #     - db

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb #Initial database
    # ports:
    #   - '3306:3306'   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8889:80'
    environment:
      PMA_HOST: mysql
volumes:
  mysql-storage:
