version: '3'

services:
  symfony:
    container_name: symfony
    build: .
    ports:
      - "9091:8000"
    command: "php bin/console server:run 0.0.0.0:8000"
    volumes:
      - ./hello-world:/var/www/html
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_DATABASE: my_database
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: aaa123
  #     MYSQL_ROOT_PASSWORD: aaa123
