FROM php:7.4-fpm

RUN apt-get update \
    && apt-get install -y \
        git \
        unzip \
        libicu-dev \
    && docker-php-ext-install \
        intl \
        pdo \
        pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

WORKDIR /var/www/app

