FROM php:7.4-fpm

RUN apt-get update \
    && apt-get install -y \
        git \
        unzip \
        libicu-dev \
        libpq-dev \
    && docker-php-ext-install \
        intl \
        pdo \
        pdo_mysql \
        pdo_pgsql \
    && pecl install \
        apcu \
    && docker-php-ext-enable \
        apcu 

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
