version: '3'

services:
  symfony:
    container_name: symfony
    build: .
    ports:
      - "9091:8000"
    command: "symfony server:start"
    # environment:
    #   - DATABASE_URL="mysql://root:root@mysql:3306/${PROJECT_NAME}?serverVersion=8&charset=utf8mb4"
    volumes:
      - ./projects/${PROJECT_NAME}:/var/www/html
    env_file:
      - .env
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${PROJECT_NAME} #Initial database
    # ports:
    #   - '3306:3306'   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8889:80'
    environment:
      PMA_HOST: mysql
volumes:
  mysql-storage:
